name: CMake Single Platform

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitCommitId: '5b1214315250939257ef5d62ecdcbca18cf4fb1c'
          runVcpkgInstall: true
          vcpkgJson: true

      - name: Install dependencies
        run: vcpkg install

      - name: Debug vcpkg root
        run: echo ${{ steps.vcpkg.outputs.vcpkgRoot }}

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${{ steps.vcpkg.outputs.vcpkgRoot }}/scripts/buildsystems/vcpkg.cmake
        env:
          VCPKG_ROOT: ${{ steps.vcpkg.outputs.vcpkgRoot }} 

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build
