name: CMake Single Platform

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.5

      - name: Install dependencies
        run: vcpkg install openssl nlohmann-json

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${{ steps.vcpkg.outputs.vcpkgRoot }}/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build
